baseURL = "https://krabf.com"
languageCode = "en-us"
title = "Kushaiah Felisilda"

summaryLength = 1_000_000
rssLimit = 10
enableGitInfo = true
enableZoom = true
block = true

[taxonomies]
  category = "categories"

[permalinks]
  blog = "/:slug"
  coffee = "/coffee/:slug"
  categories = "/:title"
  tags = "/tags/:title"
  projects = ":slug"

[params]
  name = "Kushaiah Felisilda"
  image = "media/og.jpg"
  description = "Kushaiah Felisilda’s personal website — films, filmmaking, technology, photography & more."
  

[outputs]
  home = ["HTML", "RSS"]

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
      unsafe = true
      block = true
      title = true
  [markup.goldmark.parser.attribute]
      unsafe = true
      block = true
      title = true
  [markup.tableOfContents]
    ordered = true
