baseURL = "https://krabf.com"
languageCode = "en-us"
title = "Kushaiah Felisilda"
summaryLength = 1_000_000
rssLimit = 10
enableGitInfo = true
enableZoom = true
block = true

[taxonomies]
  category = "categories"
  keyword = "keywords"

[permalinks]
  blog = "/:slug"
  coffee = "/coffee/:slug"
  categories = "/categories/:slug"
  tags = "/tags/:title"

[params]
  name = "Kushaiah Felisilda"
  ogimage = "/media/og.jpg"
  description = "Kushaiah Felisilda's personal website — films, filmmaking, technology, photography & more."
  fediCreator = "@krabf@mastodon.social"

[params.Author]
  name = "Kushaiah Felisilda"
  email = "krabfx@gmail.com"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  links = ["HTML", "RSS"]

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
    block = true
    title = true
  [markup.goldmark.parser.attribute]
    unsafe = true
    block = true
    title = true
  [markup.tableOfContents]
    ordered = true

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5