baseURL = "https://krabf.com/"
languageCode = "en-us"
title = "Kushaiah Felisilda"

summaryLength = 1_000_000
rssLimit = 10
enableGitInfo = true

[taxonomies]
  category = "categories"

[permalinks]
  posts = "/:slug"
  coffee = "/coffee/:slug"
  categories = "/:title"
  tags = "/tags/:title"
   projects = ":slug"

[author]
  name = "Kushaiah Felisilda"

[outputs]
  home = ["HTML", "RSS"]

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    ordered = true
