[build]
command = "hugo --minify"
publish = "public"

[build.environment]
HUGO_VERSION = "0.148.0"
HUGO_ENV = "production"
TZ = "Asia/Manila"

[[redirects]]
from = "/posts"
to = "/"

[[redirects]]
from = "/2016/:post"
to = "/:post"

[[redirects]]
from = "/2017/:post"
to = "/:post"

[[redirects]]
from = "/2018/:post"
to = "/:post"

[[redirects]]
from = "/posts/2016/:post"
to = "/:post"

[[redirects]]
from = "/posts/2017/:post"
to = "/:post"

[[redirects]]
from = "/posts/2018/:post"
to = "/:post"

[[redirects]]
from = "/feed"
to = "/index.xml"

[[redirects]]
from = "/feed/articles"
to = "/articles/index.xml"

